// test_data_loader.cpp -- the loose-data loader (015 area 3, phases 2, 2b, 2c).
//
// This compiles the SHIPPED windward/wind22/src/datafile.cpp -- the real text,
// not a model of it -- against tests/data/shim, and drives it over a REAL
// temporary directory tree built here. What the checks observe is therefore the
// function that ships.
//
// The shim's CFile records every path the loader tries (g_openLog). That is the
// only way to see a case-folding decision on Windows, where the filesystem is
// case-insensitive and both spellings would open the same file.
//
// Covered: loose nested, loose flat, the flat probe's leaf-only case fold, the
// patch ROOT keeping its case (phase 2c), the FVER version gate, fallback to
// the container, loose-wins-over-container precedence, the manifest marker and
// the root it selects (phase 2b), the registry pin written only for a container
// that opened, OpenAsFile's name-as-given try, and GetContainerEntrySize.
//
// Usage: test_data_loader.exe [scratch dir]   (default %TEMP%\en_dataloader_test)

#include "../ai/microtest.h"

#include "stdafx.h"              // the shim
#include "datafile_under_test.h"  // the shipped datafile.h, generated by the runner
#include "w22_settings.h"        // the shim's profile store

#include <direct.h>
#include <io.h>
#include <string>
#include <vector>

// The production loader, compiled into this fixture.
#include "../../windward/wind22/src/datafile.cpp"

std::vector<std::string> g_openLog;
std::vector<std::string> g_mmioLog;
std::vector<std::string> g_msgBoxes;

int EnTestMessageBox( HWND, const char* pText, const char*, UINT )
{
    g_msgBoxes.push_back( pText ? pText : "" );
    return IDOK;
}

namespace w22 {
TestProfile& Profile( )
{
    static TestProfile p;
    return p;
}
}  // namespace w22

namespace {

typedef std::vector<unsigned char> Bytes;

std::string g_root;  // scratch directory, absolute

void PutU32LE( Bytes& b, unsigned long v )
{
    b.push_back( (unsigned char)( v & 0xff ) );
    b.push_back( (unsigned char)( ( v >> 8 ) & 0xff ) );
    b.push_back( (unsigned char)( ( v >> 16 ) & 0xff ) );
    b.push_back( (unsigned char)( ( v >> 24 ) & 0xff ) );
}
void PutName( Bytes& b, const char* p4 )
{
    for ( int i = 0; i < 4; i++ ) b.push_back( (unsigned char)p4[i] );
}

// A minimal but REAL .rif: RIFF <form> [ LIST FVER [ DATA <short ver> ] ]
// [ LIST <form> [ DATA <marker string> ] ]. The marker is how a check tells
// which copy of an entry the loader actually returned.
Bytes MakeRif( const char* pForm, int iVer, const std::string& sMarker )
{
    Bytes inner;
    PutName( inner, "DATA" );
    PutU32LE( inner, 2 );
    inner.push_back( (unsigned char)( iVer & 0xff ) );
    inner.push_back( (unsigned char)( ( iVer >> 8 ) & 0xff ) );

    Bytes fver;
    PutName( fver, "LIST" );
    PutU32LE( fver, (unsigned long)( 4 + inner.size( ) ) );
    PutName( fver, "FVER" );
    fver.insert( fver.end( ), inner.begin( ), inner.end( ) );

    Bytes mark;
    PutName( mark, "DATA" );
    PutU32LE( mark, (unsigned long)sMarker.size( ) );
    mark.insert( mark.end( ), sMarker.begin( ), sMarker.end( ) );
    if ( sMarker.size( ) & 1 ) mark.push_back( 0 );

    Bytes body;
    PutName( body, "LIST" );
    PutU32LE( body, (unsigned long)( 4 + mark.size( ) ) );
    PutName( body, pForm );
    body.insert( body.end( ), mark.begin( ), mark.end( ) );

    Bytes out;
    PutName( out, "RIFF" );
    PutU32LE( out, (unsigned long)( 4 + fver.size( ) + body.size( ) ) );
    PutName( out, pForm );
    out.insert( out.end( ), fver.begin( ), fver.end( ) );
    out.insert( out.end( ), body.begin( ), body.end( ) );
    return out;
}

void MakeDirs( const std::string& sPath )
{
    std::string s;
    for ( size_t i = 0; i < sPath.size( ); i++ )
    {
        s += sPath[i];
        if ( sPath[i] == '\\' || sPath[i] == '/' ) _mkdir( s.c_str( ) );
    }
    _mkdir( sPath.c_str( ) );
}

void WriteFile( const std::string& sPath, const Bytes& b )
{
    size_t slash = sPath.find_last_of( "\\/" );
    if ( slash != std::string::npos ) MakeDirs( sPath.substr( 0, slash ) );
    FILE* fp = NULL;
    fopen_s( &fp, sPath.c_str( ), "wb" );
    if ( fp == NULL ) return;
    if ( !b.empty( ) ) fwrite( &b[0], 1, b.size( ), fp );
    fclose( fp );
}
void WriteText( const std::string& sPath, const std::string& s )
{
    Bytes b( s.begin( ), s.end( ) );
    WriteFile( sPath, b );
}
void Unlink( const std::string& sPath ) { _unlink( sPath.c_str( ) ); }

bool LoggedOpen( const char* pSubstr )
{
    for ( size_t i = 0; i < g_openLog.size( ); i++ )
        if ( g_openLog[i].find( pSubstr ) != std::string::npos ) return true;
    return false;
}
bool LoggedExact( const std::string& s )
{
    for ( size_t i = 0; i < g_openLog.size( ); i++ )
        if ( g_openLog[i] == s ) return true;
    return false;
}
bool MmioOpened( const std::string& s )
{
    for ( size_t i = 0; i < g_mmioLog.size( ); i++ )
        if ( g_mmioLog[i] == s ) return true;
    return false;
}
void ResetLogs( )
{
    g_openLog.clear( );
    g_mmioLog.clear( );
    g_msgBoxes.clear( );
}

const int kRifVer = 10;  // VER_RIFF in the shipped data set

//---------------------------------------------------------------------------

void TestLooseNestedWins( )
{
    const std::string sData = g_root + "\\Loose\\data";
    WriteText( sData + "\\manifest.txt", "units/units.rif 1 x\n" );
    WriteFile( sData + "\\units\\units.rif", MakeRif( "UNIT", kRifVer, "NESTED" ) );
    WriteFile( sData + "\\units.rif", MakeRif( "UNIT", kRifVer, "FLAT" ) );

    CDataFile df;
    df._Init( NULL, sData.c_str( ), kRifVer );
    ResetLogs( );

    CMmio* p = df.OpenAsMMIO( "units", "UNIT" );
    CHECK( p != NULL );
    CHECK( MmioOpened( sData + "\\units\\units.rif" ) );
    CHECK( !MmioOpened( sData + "\\units.rif" ) );
    delete p;
    df.Close( );
}

void TestLooseFlatWhenNoNested( )
{
    const std::string sData = g_root + "\\Flat\\data";
    WriteFile( sData + "\\units.rif", MakeRif( "UNIT", kRifVer, "FLAT" ) );

    CDataFile df;
    df._Init( NULL, sData.c_str( ), kRifVer );
    ResetLogs( );

    CMmio* p = df.OpenAsMMIO( "units", "UNIT" );
    CHECK( p != NULL );
    CHECK( MmioOpened( sData + "\\units.rif" ) );
    delete p;
    df.Close( );
}

void TestFlatProbeFoldsTheLeafNotTheRoot( )
{
    // The phase-2c instrument. The patch ROOT has capitals in it and the entry
    // NAME is upper case. What the loader tries must be <Root as given> +
    // "\units.rif" -- leaf folded, root untouched.
    const std::string sData = g_root + "\\MixedCase\\Data";
    WriteFile( sData + "\\units.rif", MakeRif( "UNIT", kRifVer, "FLAT" ) );

    CDataFile df;
    df._Init( NULL, sData.c_str( ), kRifVer );
    ResetLogs( );

    CMmio* p = df.OpenAsMMIO( "UNITS", "UNIT" );
    CHECK( p != NULL );
    delete p;

    // nested probe: root as given + lower-cased relative path
    CHECK( LoggedExact( sData + "\\units\\units.rif" ) );
    // flat probe: root as given + lower-cased leaf
    CHECK( LoggedExact( sData + "\\units.rif" ) );
    // and NOTHING was tried with the root folded
    std::string sFolded = sData;
    for ( size_t i = 0; i < sFolded.size( ); i++ ) sFolded[i] = (char)tolower( (unsigned char)sFolded[i] );
    CHECK( !LoggedOpen( sFolded.c_str( ) ) );

    df.Close( );
}

void TestFverMismatchRejectsTheLooseCopy( )
{
    // A loose entry of the WRONG version must not be served; with no container
    // there is nothing to fall back to, so the open fails.
    const std::string sData = g_root + "\\BadVer\\data";
    WriteFile( sData + "\\units\\units.rif", MakeRif( "UNIT", kRifVer + 1, "STALE" ) );

    CDataFile df;
    df._Init( NULL, sData.c_str( ), kRifVer );
    ResetLogs( );

    bool bThrew = false;
    try
    {
        CMmio* p = df.OpenAsMMIO( "units", "UNIT" );
        delete p;
    }
    catch ( ... )
    {
        bThrew = true;
    }
    CHECK( bThrew );
    CHECK( LoggedOpen( "units\\units.rif" ) );  // it was found...
    df.Close( );
}

//---------------------------------------------------------------------------
//  A synthetic WSDF container: magic, table size, then (len,name,offset)* and
//  the entry payloads concatenated in table order.
//---------------------------------------------------------------------------

struct ContainerEntry
{
    std::string sName;
    Bytes       payload;
};

void WriteContainer( const std::string& sPath, const std::vector<ContainerEntry>& entries )
{
    LONG cbTable = 0;
    for ( size_t i = 0; i < entries.size( ); i++ )
        cbTable += (LONG)( 4 + entries[i].sName.size( ) + 1 + 4 );

    Bytes out;
    PutName( out, "WSDF" );
    PutU32LE( out, (unsigned long)cbTable );

    unsigned long off = (unsigned long)( 8 + cbTable );
    Bytes         table;
    for ( size_t i = 0; i < entries.size( ); i++ )
    {
        PutU32LE( table, (unsigned long)( entries[i].sName.size( ) + 1 ) );
        for ( size_t j = 0; j < entries[i].sName.size( ); j++ ) table.push_back( (unsigned char)entries[i].sName[j] );
        table.push_back( 0 );
        PutU32LE( table, off );
        off += (unsigned long)entries[i].payload.size( );
    }
    out.insert( out.end( ), table.begin( ), table.end( ) );
    for ( size_t i = 0; i < entries.size( ); i++ )
        out.insert( out.end( ), entries[i].payload.begin( ), entries[i].payload.end( ) );

    WriteFile( sPath, out );
}

std::vector<ContainerEntry> StockContainer( )
{
    std::vector<ContainerEntry> v;
    ContainerEntry              e1;
    e1.sName   = "units\\units.rif";
    e1.payload = MakeRif( "UNIT", kRifVer, "CONTAINER" );
    v.push_back( e1 );
    ContainerEntry e2;
    e2.sName = "files\\stdgta.dat";
    const char* pGta = "stdgta-bytes-0123456789";
    e2.payload.assign( (const unsigned char*)pGta, (const unsigned char*)pGta + strlen( pGta ) );
    v.push_back( e2 );
    ContainerEntry e3;
    e3.sName   = "research\\research.rif";
    e3.payload = MakeRif( "RSRH", kRifVer, "CONTAINER" );
    v.push_back( e3 );
    return v;
}

void TestContainerFallbackAndLoosePrecedence( )
{
    const std::string sDir = g_root + "\\Both";
    const std::string sDat = sDir + "\\ENations.dat";
    const std::string sData = sDir + "\\data";
    WriteContainer( sDat, StockContainer( ) );

    // No loose units.rif yet: the container must serve it.
    MakeDirs( sData );
    {
        CDataFile df;
        df._Init( sDat.c_str( ), sData.c_str( ), kRifVer );
        ResetLogs( );
        CMmio* p = df.OpenAsMMIO( "units", "UNIT" );
        CHECK( p != NULL );
        CHECK( MmioOpened( sDat ) );  // came out of the container
        delete p;
        df.Close( );
    }

    // Now add a VALID loose copy with a different marker: the loose copy wins.
    WriteFile( sData + "\\units\\units.rif", MakeRif( "UNIT", kRifVer, "LOOSE" ) );
    {
        CDataFile df;
        df._Init( sDat.c_str( ), sData.c_str( ), kRifVer );
        ResetLogs( );
        CMmio* p = df.OpenAsMMIO( "units", "UNIT" );
        CHECK( p != NULL );
        CHECK( MmioOpened( sData + "\\units\\units.rif" ) );
        CHECK( !MmioOpened( sDat ) );
        delete p;
        df.Close( );
    }

    // And a loose copy of the WRONG version falls through to the container
    // rather than failing (the designed fallback).
    WriteFile( sData + "\\units\\units.rif", MakeRif( "UNIT", kRifVer + 1, "STALE" ) );
    {
        CDataFile df;
        df._Init( sDat.c_str( ), sData.c_str( ), kRifVer );
        ResetLogs( );
        CMmio* p = df.OpenAsMMIO( "units", "UNIT" );
        CHECK( p != NULL );
        CHECK( MmioOpened( sDat ) );
        delete p;
        df.Close( );
    }
    Unlink( sData + "\\units\\units.rif" );
}

void TestGetContainerEntrySize( )
{
    const std::string sDir = g_root + "\\Sizes";
    const std::string sDat = sDir + "\\ENations.dat";
    const std::vector<ContainerEntry> v = StockContainer( );
    WriteContainer( sDat, v );

    CDataFile df;
    df._Init( sDat.c_str( ), NULL, kRifVer );

    DWORD dw = 0;
    CHECK( df.GetContainerEntrySize( "files\\stdgta.dat", dw ) );
    CHECK_EQ( dw, (DWORD)v[1].payload.size( ) );

    // First entry: bounded by the next offset, not by EOF.
    CHECK( df.GetContainerEntrySize( "units\\units.rif", dw ) );
    CHECK_EQ( dw, (DWORD)v[0].payload.size( ) );

    // Last entry: bounded by EOF.
    CHECK( df.GetContainerEntrySize( "research\\research.rif", dw ) );
    CHECK_EQ( dw, (DWORD)v[2].payload.size( ) );

    // Case-insensitive on the key, and unknown names say so.
    CHECK( df.GetContainerEntrySize( "FILES\\STDGTA.DAT", dw ) );
    CHECK_EQ( dw, (DWORD)v[1].payload.size( ) );
    CHECK( !df.GetContainerEntrySize( "no\\such.rif", dw ) );

    df.Close( );

    // With no container open there is nothing to measure.
    CDataFile dfLoose;
    dfLoose._Init( NULL, ( g_root + "\\Flat\\data" ).c_str( ), kRifVer );
    CHECK( !dfLoose.GetContainerEntrySize( "files\\stdgta.dat", dw ) );
    dfLoose.Close( );
}

void TestOpenAsFileNameAsGivenThenFilesFallback( )
{
    const std::string sDir  = g_root + "\\Files";
    const std::string sData = sDir + "\\data";
    WriteText( sData + "\\files\\stdgta.dat", "LOOSE-GTA" );

    CDataFile df;
    df._Init( NULL, sData.c_str( ), kRifVer );
    ResetLogs( );

    CFile* pf = df.OpenAsFile( "stdgta.dat" );
    CHECK( pf != NULL );
    if ( pf )
    {
        char buf[16] = { 0 };
        pf->Read( buf, 9 );
        CHECK( strcmp( buf, "LOOSE-GTA" ) == 0 );
        // The name-as-given try runs FIRST and is what makes a relative loose
        // path (music.rif's case) work; here it misses and the files\ fallback
        // resolves it.
        CHECK( !g_openLog.empty( ) && g_openLog[0] == "stdgta.dat" );
        CHECK( LoggedExact( sData + "\\files\\stdgta.dat" ) );
        pf->Close( );
        delete pf;
    }
    df.Close( );
}

void TestManifestSelectsTheRootAndRetiresThePin( )
{
    // phase 2b: the marker's directory becomes the patch root, and phase 2's
    // pin rule: Init writes Game\DataFile only when a container really opened.
    const std::string sDir  = g_root + "\\LooseOnly";
    const std::string sData = sDir + "\\data";
    WriteText( sData + "\\manifest.txt", "units/units.rif 1 x\n" );
    WriteFile( sData + "\\units\\units.rif", MakeRif( "UNIT", kRifVer, "LOOSE" ) );

    // A container path that does NOT exist: _Init must not throw, because the
    // marker says loose-only is intended.
    CDataFile df;
    bool      bThrew = false;
    try
    {
        df._Init( ( sDir + "\\nosuch.dat" ).c_str( ), sData.c_str( ), kRifVer );
    }
    catch ( ... )
    {
        bThrew = true;
    }
    CHECK( !bThrew );

    ResetLogs( );
    CMmio* p = df.OpenAsMMIO( "units", "UNIT" );
    CHECK( p != NULL );
    CHECK( MmioOpened( sData + "\\units\\units.rif" ) );
    delete p;
    df.Close( );

    // Without the marker the same missing container DOES throw (the picker path).
    Unlink( sData + "\\manifest.txt" );
    CDataFile df2;
    bThrew = false;
    try
    {
        df2._Init( ( sDir + "\\nosuch.dat" ).c_str( ), sData.c_str( ), kRifVer );
    }
    catch ( ... )
    {
        bThrew = true;
    }
    CHECK( bThrew );
    df2.Close( );
}

void TestPinWrittenOnlyForAContainerThatOpened( )
{
    // Phase 2's pin rule: Init writes Game\DataFile back only when a container
    // actually opened, so a loose-only run cannot pin a dead path.
    //
    // These run on the GLOBAL theDataFile on purpose: CDataFile::Init calls
    // theDataFile._Init( ) by name and then tests its OWN m_pDataFile, so the
    // guard is only meaningful on that one instance. (Pre-existing shape - the
    // game has exactly one CDataFile - but it makes Init untestable on any
    // other object, and the check would pass vacuously on a local one.)
    const std::string sDir  = g_root + "\\Pin";
    const std::string sData = sDir + "\\data";
    WriteText( sData + "\\manifest.txt", "units/units.rif 1 x\n" );
    WriteFile( sData + "\\units\\units.rif", MakeRif( "UNIT", kRifVer, "LOOSE" ) );
    WriteContainer( sDir + "\\real.dat", StockContainer( ) );

    char szCwd[MAX_PATH] = { 0 };
    ::GetCurrentDirectoryA( sizeof( szCwd ), szCwd );
    ::SetCurrentDirectoryA( sDir.c_str( ) );

    // Loose-only: the pinned path does not exist and there is no container
    // beside the exe either, so _Init falls into loose-only mode.
    w22::Profile( ).vals["Game\\DataFile"] = ( sDir + "\\dead.dat" );
    w22::Profile( ).vals["Game\\Patch"]    = "data";
    w22::Profile( ).writes                 = 0;

    CHECK( theDataFile.Init( "ENations.dat", kRifVer, FALSE ) );
    CHECK_EQ( w22::Profile( ).writes, 0 );
    CHECK( std::string( w22::GetProfileString( "Game", "DataFile", "" ) ) == ( sDir + "\\dead.dat" ) );
    theDataFile.Close( );

    // A real container: the pin IS written back, unchanged behaviour.
    w22::Profile( ).vals["Game\\DataFile"] = ( sDir + "\\real.dat" );
    w22::Profile( ).writes                 = 0;
    CHECK( theDataFile.Init( "ENations.dat", kRifVer, FALSE ) );
    CHECK_EQ( w22::Profile( ).writes, 1 );
    theDataFile.Close( );

    ::SetCurrentDirectoryA( szCwd );
}

}  // namespace

int main( )
{
    // The scratch directory comes from the environment, NOT from argv: the
    // loader's own Init() treats the first command-line argument as a .dat path
    // (datafile.cpp, PathGetArgsA), so a fixture that took one would silently
    // override the pin it is trying to check.
    const char* pEnv = getenv( "EN_DATA_TEST_DIR" );
    if ( pEnv && *pEnv )
        g_root = pEnv;
    else
    {
        char szTmp[MAX_PATH] = { 0 };
        ::GetTempPathA( sizeof( szTmp ), szTmp );
        g_root = std::string( szTmp ) + "en_dataloader_test";
    }
    MakeDirs( g_root );

    TestLooseNestedWins( );
    TestLooseFlatWhenNoNested( );
    TestFlatProbeFoldsTheLeafNotTheRoot( );
    TestFverMismatchRejectsTheLooseCopy( );
    TestContainerFallbackAndLoosePrecedence( );
    TestGetContainerEntrySize( );
    TestOpenAsFileNameAsGivenThenFilesFallback( );
    TestManifestSelectsTheRootAndRetiresThePin( );
    TestPinWrittenOnlyForAContainerThatOpened( );

    return microtest::Summary( );
}
