//---------------------------------------------------------------------------
// win32_resources_linux.cpp — LoadStringA backing for the Linux build.
//
// The Windows build compiles lastplnt.rc, whose STRINGTABLE feeds runtime
// ::LoadStringA(GetModuleHandleA(NULL), id, ...) calls (e.g. EnSettings.cpp).
// gcc/CMake cannot compile a .RC, so lastplnt.rc is dropped from the Linux
// source list and the string table is provided here as a compiled-in map.
//
// The table is intentionally empty for the initial bring-up: a missing IDS_*
// degrades gracefully to an empty string (callers treat that as "no override").
// Once the game runs, enumerate which IDS_* are actually loaded in single-player
// and populate g_stringTable from lastplnt.rc's STRINGTABLE. Linux build only.
//---------------------------------------------------------------------------

#ifdef _WIN32
#error "win32_resources_linux.cpp is Linux-only and must not be compiled on Windows"
#endif

#include "win32_compat.h"
#include "resource.h"   // IDS_* ids (plain #defines; no Win32/MFC pulls)

#include <unordered_map>
#include <string>

namespace {
// id -> string. Populated from lastplnt.rc's STRINGTABLE as runtime needs surface.
// MP-network error strings (IDS_VP*_FAILED, 230-234) surfaced EMPTY on Linux during the
// discover/create/join flow (EnMessageBox in netapi.cpp) — e.g. a failed join showed a
// blank message box. Text copied verbatim from lastplnt.rc's STRINGTABLE.
const std::unordered_map<UINT, std::string>& string_table() {
    static const std::unordered_map<UINT, std::string> t = {
        { IDS_VPSTARTUP_FAILED, "The Network layer could not initialize.\nYou may want to try a different network connection type." },
        { IDS_VPCREATE_FAILED,  "The network layer could not create a communication channel.\nYou might want to try closing another network application\nyou are running and then try again." },
        { IDS_VPENUM_FAILED,    "The network layer could not ask for a list of games.\nYou may want to try a different network connection type." },
        { IDS_VPJOIN_FAILED,    "The network layer could not connect to the requested game.\nThe game may have already started." },
        { IDS_VPSEND_FAILED,    "The network layer could not talk to one of the other player's computers.\nYou may want to try to reconnect." },
        // MP session-close / game-start strings: these surfaced as BLANK message
        // boxes during the live Win-host↔Linux-client test (the rand-mismatch
        // disconnect showed an empty box — undiagnosable from the operator's
        // seat). Keep the %1 placeholder VERBATIM from lastplnt.rc: this port's
        // strPrintf/EnLoadStdString path uses MFC FormatMessage-style %1/%2
        // positional args, NOT printf %s (a live disconnect printed literal
        // "The game %s" when I wrongly used %s here).
        { IDS_RAND_MISMATCH,    "Did not generate identical world to server.\nYou have been disconnected from the game.\nYou can rejoin the game and it will then copy the world to\nyou (much slower but a guaranteed match)." },
        { IDS_JOIN_UNJOIN,      "The game %1\nhas disconnected from the net." },
        { IDS_SAVE_CLOSE,       "The game %1\nhas disconnected from the net.\nDo you wish to save the existing game?" },
        { IDS_JOIN_FILE_ERROR,  "Could not receive game from server" },
        { IDS_UNKNOWN,          "{unknown}" },
        // MP player-notify popups (CDlgModelessMsg): missing → the recurring
        // BLANK-body "Enemy Nations" dialog seen at every live game start
        // (IDS_MSG_NET_GOODBYE fired empty). %1/%2 positional (strPrintf), not %s.
        { IDS_MSG_NET_GOODBYE,  "Player %1 has disconnected from the game" },
        { IDS_MSG_JOIN_FAILED,  "You cannot join game%1.\nThe network returned error %2." },
        { IDS_JOIN_LOAD_FILE,   "Receiving game..." },
        // World/minimap window title (CWndWorld::CommandCenterChange) surfaced EMPTY on
        // Linux — the panel title bar went blank once the rocket landed. Title + the
        // facing-direction %1 args, verbatim from lastplnt.rc.
        { IDS_WORLD_TITLE_MAP,   "World Map (%1)" },
        { IDS_WORLD_TITLE_RADAR, "Radar (%1)" },
        { IDS_WORLD_NE,          "NE" },
        { IDS_WORLD_SE,          "SE" },
        { IDS_WORLD_SW,          "SW" },
        { IDS_WORLD_NW,          "NW" },
        // End-game cut-scene / game-over strings surfaced EMPTY on mac/Linux: the
        // win/lose end screen (SDL2CutSceneDialog, fed by EnLoadStdString) drew a BLANK
        // title — the "You Lost" / "You have conquered the planet" text never rendered
        // over the LS/WN painting (operator-reported on a HARD single-player defeat,
        // 2026-07-04). IDS_GAME_OVER likewise showed a blank EnMessageBox on the
        // all-humans-eliminated path (mainloop.cpp). Text verbatim from lastplnt.rc.
        { IDS_YOU_WON,          "You have conquered the planet" },
        { IDS_PLAYER_WON,       "%1 has conquered the planet" },
        { IDS_YOU_LOST,         "You Lost" },
        { IDS_YOU_END_SCENARIO, "Mission Completed" },
        { IDS_GAME_OVER,        "The game has ended" },
        // --- auto-filled from lastplnt.rc STRINGTABLE (parity-checked against the
        // hand-written entries above; %1/%2 positional args kept verbatim). Fixes the
        // blank-text windows on POSIX (e.g. IDS_EVENT_DEAD 'Player %1 has died' on
        // enemy elimination). Generated 2026-07-20; regenerate via tools if lastplnt.rc changes.
        { IDS_MAIN_TITLE,              "Second Chance" },
        { IDS_TITLE_AREA_MAP,          "Nothing Selected" },
        { IDS_TITLE_PLAYERS,           "Players Joining - [%1]" },
        { IDS_TITLE_CHAT_WND,          "Intraplanetary Communication" },
        { IDS_TITLE_BUILDINGS,         "Existing Buildings" },
        { IDS_TITLE_AREA_MAP_MULTI,    "%1 Units Selected" },
        { IDS_TITLE_VEHICLES,          "Existing Vehicles" },
        { IDH_AREA_CLOCK,              "Turns the map clockwise" },
        { IDH_AREA_COUNTER,            "Turns the map counter-clockwise" },
        { IDH_AREA_ZOOM_IN,            "Zooms in on the map" },
        { IDH_AREA_ZOOM_OUT,           "Zooms out from the map" },
        { IDH_UNIT_BUILD,              "Select a unit to build" },
        { IDH_UNIT_REPAIR,             "Repair this building" },
        { IDH_UNIT_STOP,               "Stop construction or repair" },
        { IDH_AREA_WIN,                "Left click selects (drag a box), right click moves/attacks (drag a line move), middle button drag scrolls" },
        { IDH_AREA_WIN_BUILD,          "Click on hex for bottom corner of location for building you wish to build" },
        { IDH_AREA_WIN_MOVE,           "Click on the location you wish to have the selected vehicle(s) move to" },
        { IDS_CREATE_CHOOSE,           "Choose Race >>" },
        { IDS_CREATE_CREATE,           "Create Game >>" },
        { IDH_WORLD_WIN,               "Left click looks at a location, right click sends the selected units there, middle button drag scrolls" },
        { IDS_CREATE_PUBLISH,          "Publish Game >>" },
        { IDS_JOIN_PUBLISH,            "Publish >>" },
        { IDS_JOIN_JOIN,               "Join >>" },
        { IDH_UNIT_ROUTE,              "Setup route for vehicle" },
        { IDH_BAR_AREA,                "Bring the area map window to the top and give it the focus" },
        { IDH_BAR_WORLD,               "Bring the radar to the top and give it the focus" },
        { IDH_BAR_CHAT,                "Bring the chat window to the top and give it the focus" },
        { IDH_BAR_ADVISOR,             "Bring the advisor window to the top and give it the focus" },
        { IDH_BAR_VEHICLES,            "Bring the vehicles list window to the top and give it the focus" },
        { IDH_BAR_BUILDINGS,           "Bring the building list window to the top and give it the focus" },
        { IDH_BAR_SCIENCE,             "Bring the research window to the top and give it the focus" },
        { IDH_BAR_FILE,                "Save and Exit the game, Set options, Help, etc." },
        { IDS_JOIN_AI_0,               "Easy" },
        { IDS_JOIN_AI_1,               "Moderate" },
        { IDS_JOIN_AI_2,               "Difficult" },
        { IDS_JOIN_AI_3,               "Impossible" },
        { IDS_JOIN_SIZE_0,             "Small" },
        { IDS_JOIN_SIZE_1,             "Medium" },
        { IDS_JOIN_SIZE_2,             "Large" },
        { IDS_CREATE_NUM_PLAYERS,      "Players Joined: %1" },
        { IDS_JOIN1_TITLE,             "Join a Game" },
        { IDS_JOIN1_TITLE_SEL,         "Joined Game - [%1]" },
        { IDS_CREATE_WORLD,            "Creating the World..." },
        { IDS_MSG_UNIT_GOTO,           "Select the location to send the %1 to" },
        { IDS_AI_NAME,                 "Computer Player %1" },
        { IDS_LOAD_TERRAIN,            "Mapping planet terrain..." },
        { IDS_LOAD_STRUCTURES,         "Assembling buildings..." },
        { IDS_LOAD_TRANSPORTS,         "Assembling vehicles..." },
        { IDS_CREATE_WINDOWS,          "Creating the display..." },
        { IDS_ALLOC_MAP,               "Creating the world..." },
        { IDS_INIT_MAP,                "Building the world..." },
        { IDS_CHECK_MAP,               "Checking the world..." },
        { IDS_ASSIGN_TILES,            "Determining terrain..." },
        { IDH_AREA_WIN_RMB,            "Drag with the middle button down to scroll the map (push to a window edge to keep scrolling)" },
        { IDS_TIME_OUT,                "This is the shareware version of Second Chance which has\na play limit. You must end this game now. You can save this\ngame and continue playing with the retail version of Second Chance.\nDo you wish to save?" },
        { IDS_MULT_INST,               "You are already running a copy of Second Chance.\nDo you wish to switch to the running game (Yes)?\n(Or start a second copy of the game (No).)" },
        { IDH_WORLD_WIN_RMB,           "Drag with the middle button down to scroll the view" },
        { IDS_LOAD_FILE,               "Loading the file..." },
        { IDS_CONSTRUCTION,            "Construction costs" },
        { IDS_PEOPLE,                  "Colonists" },
        { IDS_TIME,                    "Time" },
        { IDS_OPERATING,               "Operating costs" },
        { IDS_POWER,                   "Power" },
        { IDS_GAS,                     "Gas" },
        { IDS_START_AI2,               "Tracking opponent colonies..." },
        { IDS_FOOD,                    "Food" },
        { IDS_DAMAGE,                  "damage" },
        { IDS_ROUTE_GOTO,              "Set Next" },
        { IDS_ROUTE_UNLOAD,            "Unload" },
        { IDS_ROUTE_LOAD,              "Load" },
        { IDS_ROUTE_WAYPOINT,          "Waypoint" },
        { IDS_ROUTE_DELETE,            "Delete" },
        { IDH_ROUTE_GOTO,              "Select the next location in the vehicle's route" },
        { IDH_ROUTE_UNLOAD,            "Unload all goods at this location" },
        { IDH_ROUTE_LOAD,              "Load up the vehicle at this location" },
        { IDH_ROUTE_WAYPOINT,          "Vehicle will pass over this location" },
        { IDH_ROUTE_DELETE,            "Delete this stop from the vehicle's route" },
        { IDS_NOT_MY_UNIT,             "You cannot select other player's units" },
        { IDS_SERVER_QUIT,             "This will end the game for all players.\nAre you sure you want to quit?" },
        { IDS_CLIENT_QUIT,             "This will drop you from the game.\nAre you sure you want to quit?" },
        { IDS_MAIL_SEND,               "Send Mail" },
        { IDS_MAIL_REPLY,              "Reply to Mail" },
        { IDS_MAIL_FORWARD,            "Forward Mail" },
        { IDS_MAIL_DELETE,             "Delete Mail" },
        { IDS_MAIL_REFUSE,             "Return Unread" },
        { IDS_MAIL_CHAT,               "Call to Chat" },
        { IDS_MAIL_CHAT_ANS,           "Bring up Open Chat" },
        { IDS_MAIL_VOICE,              "Call to Talk" },
        { IDS_MAIL_VOICE_ANS,          "Answer Request to Talk" },
        { IDS_MAIL_OPTIONS,            "Set Mail Options" },
        { IDS_MAIL_READ,               "Read Mail" },
        { IDS_MAIL_PREV,               "Previous Message" },
        { IDS_MAIL_NEXT,               "Next Message" },
        { IDS_START_AI1,               "Initializing the Computer Opponents" },
        { IDS_MSG_ROCKET_START,        "Choose the location to land your spaceship" },
        { IDS_MSG_ROCKET_DONE,         "Your spaceship has landed" },
        { IDS_MSG_ROCKET_WAIT,         "Spacship is waiting for clearance to land" },
        { IDS_NAME_TOO_LONG,           "Your name can not be longer than 78 characters." },
        { IDS_DESC_TOO_LONG,           "Your game name and description cannot total over 450 characters." },
        { IDS_COPYRIGHT,               "� 1995 - 1997 Windward Studios, Inc.  All Rights Reserved." },
        { IDS_AI_PLAYER,               "Computer Player %1" },
        { IDS_PREV,                    "<< &Prev" },
        { IDS_UNPUBLISH,               "&Unpublish" },
        { IDS_POS_MIN_CIV,             "Minimal Civilian" },
        { IDS_POS_FULL_CIV,            "Full Civilian" },
        { IDS_POS_MIN_COM,             "Minimal Combat" },
        { IDS_POS_FULL_COM,            "Full Combat" },
        { IDH_UNIT_RESUME,             "Resume Route, Construction, or Repair" },
        { IDH_UNIT_CANCEL,             "Cancel new building construction" },
        { IDH_UNIT_ROAD,               "Build a road" },
        { IDS_INFO_DAMAGE,             "Damage: %1%" },
        { IDS_ROUTE_OK,                "OK" },
        { IDH_ROUTE_OK,                "Closes the window and starts the vehicle" },
        { IDS_CHAT_TITLE,              "Chat - [%1]" },
        { IDS_CHAT_STATUS,             "%1 wants to chat" },
        { IDS_SAVE_FILTERS,            "Game Files (*.en)|*.en|All Files (*.*)|*.*||" },
        { IDS_SAVE_OLD,                "Do you wish to save the existing game?" },
        { IDS_SAVE_NAME,               "Save to File %1" },
        { IDS_SAVE_VER,                "This file was saved by another version of Second Chance.\nThe file is version %1\nYou are running version %2" },
        { IDS_SAVE_ERROR,              "Error saving game to file %1" },
        { IDS_LOAD_NAME,               "Loading: %1" },
        { IDS_LOAD_ERROR,              "Error loading game from file %1" },
        { IDS_ERR_CREATE,              "Could not create the game" },
        { IDS_RSRCH_NOTHING,           "Research Choices" },
        { IDS_RSRCH_TITLE,             "Researching - [%1]" },
        { IDS_SINGLE_QUIT,             "This will end the game.\nAre you sure you want to quit?" },
        { IDS_JOIN_NEW,                "New Game" },
        { IDS_JOIN_LOAD,               "Loaded Game" },
        { IDS_JOIN_INPROGRESS,         "Game In Progress" },
        { IDS_PICKING_RACE,            "Choosing Race" },
        { IDS_READY_TO_GO,             "Waiting for Others" },
        { IDS_ASK_START,               "Not all players are ready.\nAre you sure you want to start?\nPlayers not ready will be dropped." },
        { IDS_DROP_PLAYER,             "Are you sure you want to drop this player from the game?" },
        { IDS_PICKING_PLAYER,          "Choosing Player" },
        { IDH_AREA_OK_FARM,            "This is a good location for this building" },
        { IDH_AREA_BAD_FARM,           "This is a poor location for this building" },
        { IDH_AREA_NO_FARM,            "This is a useless location for this building" },
        { IDH_AREA_OK_MINE,            "This is a good location for this mine" },
        { IDH_AREA_BAD_MINE,           "This is a poor location for this mine" },
        { IDH_AREA_NO_MINE,            "This is a useless location for this mine" },
        { IDS_SAVE_EXT,                "en" },
        { IDH_AREA_RES,                "Show all mineral deposits" },
        { IDH_UNIT_CANCEL_BUILD,       "Cancel build order" },
        { IDH_UNIT_UNLOAD,             "Unload all carriers" },
        { IDH_UNIT_CANCEL_ROAD,        "Cancel building a road" },
        { IDH_AREA_WIN_ROAD,           "Select where you want a road built" },
        { IDH_AREA_WIN_REPAIR,         "Select the building to repair" },
        { IDS_ERR_LOAD_1,              "Error %1 loading the game" },
        { IDS_ERR_LOAD_2,              "Unknown error loading the game" },
        { IDS_NO_MEMORY,               "There is no available memory.\nThe game will exit." },
        { IDS_ERR_LOAD_3,              "Sorry - an unknown error occured.\r\nVersion: %1\r\nType: 0x%2, Address: 0x%3\r\nStack:0x%4,0x%5,0x%6,0x%7,0x%8" },
        { IDS_WRONG_DATA_FILE,         "This ENations.dat is for %1, version: %2.\nThis game requires %3, version: %4.\nDo you want to locate the correct file?" },
        { IDS_SAVE_ON_ERROR,           "You may be able to save your game. Because the cause of the \nerror is unknown this may not work. And if it saves, it may\nsave the game in a corrupted state. Then again, for many errors \nit can successfully save the game. Do you wish to save the game?" },
        { IDS_SAVE_ON_ERROR_FAILED,    "We were not able to save the game - sorry." },
        { IDS_EVENT_CONST_LOC,         "Pick location to construct building" },
        { IDS_EVENT_CONST_CANT,        "Can't build a %1 at the construction site" },
        { IDS_EVENT_CONST_START,       "Construction of %1 has started" },
        { IDS_EVENT_HALTED,            "Construction of a %1 has been halted" },
        { IDS_EVENT_CONST_DONE,        "A new %1 has been completed" },
        { IDS_EVENT_REPAIR_DONE,       "%1 has been repaired" },
        { IDS_EVENT_ROAD_START,        "Construction of a road has begun" },
        { IDS_EVENT_ROAD_HALTED,       "Construction of a road has halted" },
        { IDS_EVENT_ROAD_DONE,         "Construction of a road has completed" },
        { IDS_EVENT_MANF_HALT,         "%1 has halted manufacturing" },
        { IDS_EVENT_GOTO_CANT,         "%1 is stuck" },
        { IDS_EVENT_BLDG_UNDER,        "%1 is under attack" },
        { IDS_EVENT_BLDG_HURTING,      "%1 has been seriously damaged" },
        { IDS_EVENT_BLDG_DYING,        "%1 is about to be destroyed" },
        { IDS_EVENT_ATK_TARGET,        "Enemy %1 is under attack" },
        { IDS_EVENT_ATK_DESTROYED,     "Enemy %1 has been destroyed" },
        { IDS_EVENT_HAVE_MAIL,         "You have new mail" },
        { IDS_EVENT_HAVE_CALL,         "You have a call" },
        { IDS_EVENT_RSRCH_DONE,        "Research on %1 successfully completed" },
        { IDS_EVENT_MINE_EMPTY,        "%1 has extracted all available minerals" },
        { IDS_EVENT_POP_LOW,           "You need more colonists to fully staff your facilities" },
        { IDS_EVENT_GAS_LOW,           "You are running low on gasoline" },
        { IDS_EVENT_FOOD_LOW,          "You are running low on food" },
        { IDS_EVENT_POWER_LOW,         "You are not generating enough power" },
        { IDS_EVENT_GAS_OUT,           "You are out of gasoline" },
        { IDS_EVENT_FOOD_OUT,          "You are out of food - people are starving" },
        { IDS_EVENT_DEAD,              "Player %1 has died" },
        { IDS_EVENT_LEFT,              "Player %1 has left the game" },
        { IDS_EVENT_JOINED,            "Player %1 has joined the game" },
        { IDS_BUILD_PEOPLE,            "Build Personnel" },
        { IDS_ROUTE_AUTO,              "Auto" },
        { IDH_ROUTE_AUTO,              "Let game handle this vehicle" },
        { IDS_OPTIONS_ADV,             "You need to exit and  restart Second Chance for these changes to take effect" },
        { IDS_DISCOVERED_NO_TITLE,     "Discovered - []" },
        { IDS_DISCOVERED_TITLE,        "Discovered - [%1]" },
        { IDH_STAT_GAS,                "Gas: burning at %1/minute,  reserve of %2" },
        { IDH_STAT_POWER,              "Power: need %1, generating %2" },
        { IDH_STAT_PEOPLE,             "%1 Colonists: %2 working, %3 operating vehicles, %4 idle" },
        { IDH_STAT_PEOPLE2,            "%1 Colonists: %2 working, %3 driving, %4 needed" },
        { IDH_STAT_FOOD,               "Food: eating %1/minute,  reserve of %2" },
        { IDH_STAT_CLOCK,              "How long this game has been running" },
        { IDS_NO_CHAT1,                "Chat is only used in multi-player mode" },
        { IDS_NO_CHAT2,                "You must research before chat works" },
        { IDS_NO_SCIENCE,              "You must build a research facility if you wish to discover new technology" },
        { IDH_WORLD_RES,               "Displays resources on the radar" },
        { IDH_WORLD_OWNER,             "Displays all of your units on the radar" },
        { IDH_WORLD_UNITS,             "Displays visible enemy units on the radar" },
        { IDH_WORLD_VIS,               "Displays terrain visibility on the radar" },
        { IDH_WORLD_RES2,              "Displays resources on the radar" },
        { IDH_WORLD_OWNER2,            "Displays all of your buildings on the radar" },
        { IDH_WORLD_UNITS2,            "Displays visible enemy buildings on the radar" },
        { IDH_WORLD_VIS2,              "Must build Command Center to display terrain visibility on the radar" },
        { IDS_STAT_DAMAGE,             "Damage: %1%" },
        { IDS_STAT_CONST,              "%1% Construction completed" },
        { IDS_STAT_IDLE,               "idle" },
        { IDS_STAT_BUILD,              "%1 %2% constructed" },
        { IDS_STAT_REPAIR,             "%1 %2% repaired" },
        { IDS_STAT_APT,                "All Apartments: %1 occupied, %2 vacant" },
        { IDS_STAT_APT2,               "All Apartments: %1 occupied, %2 needed" },
        { IDS_STAT_OFFICE,             "All Offices: %1 occupied, %2 vacant" },
        { IDS_STAT_OFFICE2,            "All Offices: %1 occupied, %2 needed" },
        { IDS_STAT_MINE,               "Mining %1 units/minute, Remaining: %2 (denisty: %3)" },
        { IDS_STAT_MINERALS,           "%1: Quantity %2, Density %3" },
        { IDS_STAT_FARM,               "Producing %1 units/minute." },
        { IDS_STAT_POWER,              "Generating %1 units power. Full Capacity %2 units." },
        { IDS_EVENT_LOW_HOUSING,       "You need more housing for your colonists" },
        { IDS_EVENT_LOW_OFFICE,        "You need more offices for your colonists" },
        { IDS_EVENT_NEW_CRANE,         "A new crane has been built in your rocket ship" },
        { IDS_EVENT_NEW_TRUCK,         "A new truck has been built in your rocket ship" },
        { IDS_EVENT_NEW_RELATIONS,     "Player %1 attacked you, relations changed to war." },
        { IDS_NO_EMBASSY,              "You must build an embassy if you wish to change your diplomatic relations" },
        { IDH_AREA_CANT_BLDG_NEXT,     "Can't lower/raise ground to match adjoining building." },
        { IDH_AREA_CANT_WATER_NEXT,    "Can't lower ground to match adjoining water." },
        { IDH_AREA_CANT_VEH_IN_WAY,    "Can't build over the vehicle in the way." },
        { IDH_AREA_CANT_ON_WATER,      "Cannot build this building on water." },
        { IDH_AREA_CANT_NO_WATER,      "This building must be partially on water." },
        { IDH_AREA_CANT_NO_LAND_EXIT,  "Vehicles cannot exit to land." },
        { IDH_AREA_CANT_NO_WATER_EXIT, "Ships cannot exit to water." },
        { IDH_AREA_CANT_TOO_STEEP,     "The ground is too steep." },
        { IDH_WORLD_FACE,              "Must build Command Center to convert to radar" },
        { IDS_OK,                      "Play" },
        { IDS_CANCEL,                  "Exit" },
        { IDS_SAVE,                    "Save..." },
        { IDS_LOADING,                 "Loading Second Chance..." },
        { IDS_LEAVING,                 "Leaving Second Chance..." },
        { IDS_BAD_PLAYER_NUM,          "Did not receive information about joining player." },
        { IDS_EXIT_GAME,               "Closing Game..." },
        { IDS_STAT_CARRIER,            "Carrying %1 units" },
        { IDS_LOAD_TRUCK,              "Load Truck - [%1]" },
        { IDS_PAUSE_CLIENT,            "Server has paused the game" },
        { IDS_PAUSE_SERVER,            "Press CTRL-P to resume the game" },
        { IDS_EVENT_HPR_TRUCKS,        "You need more trucks" },
        { IDS_EVENT_HPR_NOPICKUP,      "Your truck cannot find any %1" },
        { IDS_EVENT_HPR_SEAPORTS,      "Your trucks need seaports" },
        { IDS_EVENT_HPR_CARGOSHIP,     "Your trucks need a cargo ship" },
        { IDS_EVENT_HPR_NOREACH,       "Your trucks cannot reach your seaport" },
        { IDS_STAT_ROCKET,             "Apartments: %1/%2  Offices: %3/%4 (need/have)  Power: %5" },
        { IDS_EVENT_CANT_BRIDGE,       "You must research bridges first" },
        { IDS_EVENT_HAVE_RADAR,        "You now have radar" },
        { IDS_ERROR_LOW_PHYS_MEM,      "Second Chance requires at least 8M of memory.\r\nDo you wish to continue?" },
        { IDS_ERROR_LOW_VIRT_MEM,      "Second Chance requires at least %1M of virtual memory.\r\nDo you wish to continue?" },
        { IDS_ERROR_LOW_AVAIL_MEM,     "There may not be enough free memory.\r\nPlease close down some other applications.\r\nDo you wish to continue?" },
        { IDS_COST,                    "cost" },
        { IDS_HAVE,                    "have" },
        { IDS_NEED,                    "need" },
        { IDS_CONTINUE,                "Continue" },
        { IDS_STAT_MATERIAL,           "Producing %1 %2/minute" },
        { IDS_ROUTE_TITLE,             "Route - [%1]" },
        { IDS_RESEARCHING,             "Researching %1" },
        { IDS_LONGEST_STRING,          "Click on the location you wish to have the selected vehicle(s) move to" },
        { IDS_EXHAUSTED,               "%1 Exhausted" },
        { IDS_WAYPOINT,                "waypoint" },
        { IDS_LOAD,                    "load" },
        { IDS_UNLOAD,                  "unload" },
        { IDS_EVENT_ROCKET_CANT_LAND,  "Your rocket cannot land here" },
        { IDS_LOAD_MUSIC,              "Arranging Music" },
        { IDS_AI_LIMIT_2_MAX,          "Your computer cannot handle more than %1 AI opponents" },
        { IDS_AI_LIMIT_MAX,            "Your computer cannot optimally handle more than %1 AI opponents.\nDo you wish to continue?" },
        { IDS_BUILDINGS,               "Buildings:" },
        { IDS_VEHICLES,                "Vehicles:" },
        { IDS_PLAYERS,                 "Players..." },
        { IDH_MAIL_READ,               "Read the selected message" },
        { IDH_MAIL_SEND,               "Send a message" },
        { IDH_MAIL_REPLY,              "Reply to the selected message" },
        { IDH_MAIL_FORWARD,            "Forward the selected message" },
        { IDH_MAIL_DELETE,             "Delete the selected message(s)" },
        { IDH_MAIL_REFUSE,             "Refuse delivery of the selected message(s)" },
        { IDH_MAIL_CHAT,               "Call up a player to chat" },
        { IDH_MAIL_CHAT_ANS,           "Bring up the Open Chat window" },
        { IDH_MAIL_OPTIONS,            "Select who you will accept calls from" },
        { IDS_GIVE_UNITS,              "Are you sure you want to give %1 building(s) and %2 vehicle(s)\nto player %3?" },
        { IDS_EVENT_HPR_NOACCESS,      "Truck is not able to find materials" },
        { IDS_LOAD_SFX,                "Loading voices..." },
        { IDH_AREA_COMBAT,             "Centers map on most recent combat" },
        { IDS_LOAD_FREIGHTER,          "Load Freighter" },
        { IDS_BUILD_VEHICLE,           "Build Vehicle" },
        { IDS_BUILD_UNIT,              "Building - [%1]" },
        { IDS_TRUCK_AUTO,              "Auto: " },
        { IDS_TRUCK_IDLE,              "idle" },
        { IDS_TRUCK_ROUTE,             "Route: " },
        { IDS_TRUCK_TRAVEL,            "traveling" },
        { IDS_PLYR_TAKEN,              "{player taken}" },
        { IDS_ERROR_NT_NET_BUG,        "There is a bug in the NT 4.0 TCP/IP stacks that will cause a GPF on some systems the second time it is opened by an application. If you GPF just restart Second Chance after each net game.\r\nDo you wish to continue?" },
        { IDS_CANT_SAVE,               "Sorry, it could not save the file:\n%1" },
        { IDS_MAX_CHAT,                "Sorry - you can only edit the last 400 characters of your message" },
        { IDS_MAX_MAIL,                "Sorry - mail messages can only be 400 characters long." },
        { IDS_VDMPLAY_VER,             "Second Chance requires VDMPlay.dll version 1.0.33 or later.\nPlease reinstall Second Chance to get the proper version of VDMPlay.dll" },
        { IDS_MSS_VER,                 "Second Chance requires MSS32.dll version 3.6A or later.\nPlease reinstall Second Chance to get the proper version of MSS32.dll" },
        { IDS_DEMO_OVER,               "You have been playing the demo version of Second Chance for a month.\nTherefore this demo will no longer run.\nIf you have enjoyed the game please consider buying the retail version." },
        { IDS_DEMO_RESEARCH_MAX,       "You have researched the maximum number of topics allowed in the demo version." },
        { IDS_NONE,                    "{pinging %1 ...}" },
        { IDS_YOUR_ADDR,               "Your net address: " },
        { IDS_IS_ADDR,                 "Internet server address: " },
        { IDS_EN_VER,                  "Second Chance version: " },
        { IDS_VP_VER,                  "VDMPlay version: " },
        { IDS_DEMO_25,                 "You have played this demo of Second Chance %1 times.\nThis game cost over $500,000.00 to produce.\nSales locations are listed at www.windward.net.\nIf you like the game will you buy a copy?" },
        { IDS_ADDR_OFF,                "<< Address" },
        { IDS_ADDR,                    "Address >>" },
        { IDS_ADV_DEPTH,               "You should not force bitmaps to the screen depth unless you\n have at least a Pentium Pro/200, 32M of RAM, and 16X\nCD-ROM drive.\nDepths other than 8-bit will take 3 - 4 times longer to\nload, require 3 - 4 times the memory, and require\n2 - 4 times the processing power to render." },
        { IDS_ADV_ZOOM,                "You should not force zoom 0 unless you have at least 32M\nof RAM, and 16X CD-ROM drive. Zoom level 0 will take\n4 - 5 times longer to load and require 4 - 5 times the memory." },
        { IDS_ERROR_LOW_ZOOM,          "You have set Second Chance to load the zoom 0 sprites and you do not have enough memory to run at this setting. Please change the setting back to based on free memory.\r\nDo you wish to run with no zoom 0 (will not change the permanent setting)?" },
        { IDS_ERROR_LOW_ZOOM2,         "You have set Second Chance to load the zoom 0 sprites and you do not have enough processing power to load quickly at this setting. Please change the setting back to based on free memory.\r\nDo you wish to run with no zoom 0 (will not change the permanent setting)?" },
        { IDS_ERROR_LOW_MUSIC,         "You have set Second Chance to play digital audio music and you do not have enough processor power (P/120 min) and/or CD speed (6X min) to run at this setting. Please change the setting back to based on speed.\r\nDo you wish to run with MIDI (will not change the permanent setting)?" },
        { IDS_HPR_BLOCKED,             "A truck cannot enter a building (blocked)" },
        { IDS_AI_TAKEOVER,             "The Computer is taking over player %1" },
        { IDS_KILLER_RES,              "Your CPU cannot effectively render at your present screen resolution of %1. Do you want Second Chance to set your screen resolution to %2?\r\n(This can be permanently changed in Advanced Options. Will unset when you exit the game.)" },
        { IDS_SERVER,                  "Server" },
        { IDS_SAVE_REMOTE,             "Updating remote data" },
        { IDS_SAVE_LOCAL,              "Pausing AI players" },
        { IDS_SAVE_DATA,               "Saving game data" },
        { IDS_SAVE_COMPRESS,           "Compressing block %1" },
        { IDS_SAVE_WRITE,              "Writing game to disk" },
        { IDS_OUT_OF_MEMORY,           "You are out of memory - please increase the size of your virtual memory" },
        { IDS_BAD_REG,                 "Could not execute your browser.\nPlease point your browser at www.windward.net/register" },
        { IDS_GOOD_REG,                "Please wait for your browser to start.\nPress OK after you have exited your browser." },
        { IDS_EN_LOGGING,              "You have logging turned on.\nThis was done by setting:\n     [Advanced]\n     Log=1\nin the file enations.ini.\nThis will slow down the game" },
        { IDS_VP_LOGGING,              "You have vdmplay logging turned on.\nThis was done by setting:\n     [Vdmplay]\n     UseLogFile=1\nin the file vdmplay.ini.\nThis will slow down the game" },
    };
    return t;
}
} // namespace

extern "C" int LoadStringA(HINSTANCE /*inst*/, UINT id, LPSTR buf, int bufMax) {
    if (!buf || bufMax <= 0) return 0;
    const std::unordered_map<UINT, std::string>& t = string_table();
    std::unordered_map<UINT, std::string>::const_iterator it = t.find(id);
    if (it == t.end()) { buf[0] = '\0'; return 0; }
    int n = (int)it->second.size();
    if (n > bufMax - 1) n = bufMax - 1;
    memcpy(buf, it->second.data(), n);
    buf[n] = '\0';
    return n;
}
